// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhS0h9t0xiHu77lp7Fuqp9gyLcdgtDW0',
    appId: '1:1068245355853:web:1cbc0015cada9a13e17b04',
    messagingSenderId: '1068245355853',
    projectId: 'fir-chat-5040f',
    authDomain: 'fir-chat-5040f.firebaseapp.com',
    storageBucket: 'fir-chat-5040f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uKASpFAglaEX4SOYG-Wx5nTWRLHObEg',
    appId: '1:1068245355853:android:202b962e0db4e0d2e17b04',
    messagingSenderId: '1068245355853',
    projectId: 'fir-chat-5040f',
    storageBucket: 'fir-chat-5040f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZS3w7ojPXVD3AWiJNQ3HbNlkYuWj4yk',
    appId: '1:1068245355853:ios:4723290d23c8e2aee17b04',
    messagingSenderId: '1068245355853',
    projectId: 'fir-chat-5040f',
    storageBucket: 'fir-chat-5040f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZS3w7ojPXVD3AWiJNQ3HbNlkYuWj4yk',
    appId: '1:1068245355853:ios:10b8d52e75daa748e17b04',
    messagingSenderId: '1068245355853',
    projectId: 'fir-chat-5040f',
    storageBucket: 'fir-chat-5040f.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
